/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa;

import consultas.TablaProductos;
import helpers.agregarProductos.ValidacionesProductos;
import helpers.sql.Productos;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import validaciones.Validaciones;

/**
 *
 * @author jafeth888
 */
public class AgregarDatos extends javax.swing.JFrame {
    Productos instanciaProducto=new Productos();
    TablaProductos instanciaTablaProductos=new TablaProductos();
    /**
     * Creates new form AgregarDatos
     */
    public AgregarDatos() {
        this.setContentPane(new ImagenFondo());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldCodigoDeBarra = new javax.swing.JTextField();
        labelCodigoDeBarrasExistente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textField_Descripcion = new javax.swing.JTextField();
        labelDescripcionProductoExistente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textField_Cantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFieldCostoUnitario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textFieldPrecioUnitario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textFieldCategoria = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar productos");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("CODIGO DE BARRA:");

        textFieldCodigoDeBarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldCodigoDeBarraKeyReleased(evt);
            }
        });

        labelCodigoDeBarrasExistente.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("INGRESE LA DESCRIPCION DEL PRODUCTO:");

        textField_Descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textField_DescripcionKeyReleased(evt);
            }
        });

        labelDescripcionProductoExistente.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("CANTIDAD:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("PRECIO COSTO");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("PRECIO UNITARIO");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("CATEGORIA");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registrar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldCodigoDeBarra)
                            .addComponent(labelCodigoDeBarrasExistente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField_Descripcion)
                            .addComponent(labelDescripcionProductoExistente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField_Cantidad)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldCostoUnitario)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldPrecioUnitario)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldCategoria)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCodigoDeBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCodigoDeBarrasExistente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDescripcionProductoExistente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCostoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Validaciones validacion = new Validaciones();
        String codigoBarra=textFieldCodigoDeBarra.getText(),cantidad=textField_Cantidad.getText();
        String descripcion=textField_Descripcion.getText(),precioUnitario=textFieldPrecioUnitario.getText();
        String costoUnitario=textFieldCostoUnitario.getText(),categoria=textFieldCategoria.getText();
        
        if (textField_Descripcion.getText().equals("") || textFieldPrecioUnitario.getText().equals("") || textField_Cantidad.getText().equals("") || textFieldCodigoDeBarra.getText().equals("") || textFieldCostoUnitario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "DATOS INCOMPLETOS ASEGURE QUE TODO LOS CAMPOS ESTEN RELLENOS", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (validacion.validarProductos(textFieldCodigoDeBarra.getText(),textField_Descripcion.getText()) || validacion.codigoDeBarrasYaExistente(textFieldCodigoDeBarra.getText()) ||  validacion.descripcionProductoYaExistente(textField_Descripcion.getText()))  {
            JOptionPane.showMessageDialog(null,"EL PRODUCTO YA EXISTE","Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            return;
	}
        if(textFieldCategoria.getText().toLowerCase().equals("unidades")==false) {
            if(validacion.isNumeric(textField_Cantidad.getText())==false) {
                JOptionPane.showMessageDialog(null,"solos los productos con categoria ' UNIDADES ' pueden tener numero decimal en el apartado de la cantidad");
                return;
            }
        }
        
        ValidacionesProductos validacionProducto=new ValidacionesProductos();
        /*-----VERIFICAR QUE EL PRECIO UNITARIO SEA MAYOR O IGUAL AL COSTO VENTA PARA OBTENER GANANCIAS-----*/
        if(validacionProducto.verificarPrecioUnitarioProducto(precioUnitario, costoUnitario)!=true) return;

        descripcion= descripcion.toLowerCase().trim().replaceAll("\\s{2,}", " ");//el texto no debe de tener mas de un espacio y todo en minuscula
        categoria  = categoria.  toLowerCase().trim().replaceAll("\\s{2,}", " ");
        
        instanciaProducto.registrarProducto(codigoBarra,cantidad, descripcion,precioUnitario,costoUnitario,categoria);
        
        if(VentanaPrincipal.codigoBarra.getText().equals("")) {
            instanciaTablaProductos.mostrardatosProductos("",VentanaPrincipal.jTablaProductos);
        }else {
            instanciaTablaProductos.mostrardatosProductos(VentanaPrincipal.codigoBarra.getText(),VentanaPrincipal.jTablaProductos);
        }
        JOptionPane.showMessageDialog(null, "EL PRODUCTO FUE AGREGADO CON EXITO");
        textFieldCodigoDeBarra.setText("");
        textField_Cantidad.setText("");
        textField_Descripcion.setText("");
        textFieldPrecioUnitario.setText("");
        textFieldCostoUnitario.setText("");
        textFieldCategoria.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textFieldCodigoDeBarraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldCodigoDeBarraKeyReleased
        // TODO add your handling code here:
        Validaciones validacion = new Validaciones();
        if(validacion.codigoDeBarrasYaExistente(textFieldCodigoDeBarra.getText())) {
            labelCodigoDeBarrasExistente.setText("Este codigo de barras ya existe!");
        }else {
            labelCodigoDeBarrasExistente.setText("");
        }
    }//GEN-LAST:event_textFieldCodigoDeBarraKeyReleased

    private void textField_DescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_DescripcionKeyReleased
        // TODO add your handling code here:
        Validaciones validacion = new Validaciones();
        if(validacion.descripcionProductoYaExistente(textField_Descripcion.getText())) {
            labelDescripcionProductoExistente.setText("Esta descripcion ya existe!");
        }else {
            labelDescripcionProductoExistente.setText("");
        }
    }//GEN-LAST:event_textField_DescripcionKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelCodigoDeBarrasExistente;
    private javax.swing.JLabel labelDescripcionProductoExistente;
    private javax.swing.JTextField textFieldCategoria;
    private javax.swing.JTextField textFieldCodigoDeBarra;
    private javax.swing.JTextField textFieldCostoUnitario;
    private javax.swing.JTextField textFieldPrecioUnitario;
    private javax.swing.JTextField textField_Cantidad;
    private javax.swing.JTextField textField_Descripcion;
    // End of variables declaration//GEN-END:variables

    public class ImagenFondo extends JPanel{

        @Override
        public void paint(Graphics g) {
            ImageIcon imagen = new ImageIcon(getClass().getResource("../img/fondoSecundario.png"));
            g.drawImage(imagen.getImage(),0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g); 
        }
    }

}
