/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package puntodeventa;

import helpers.Buscadores;
import helpers.TableModel;
import helpers.compras.Carrito;
import helpers.sql.Productos;
import helpers.sql.TablaApartados;
import helpers.sql.TablaCompras;
import helpers.sql.TablaDetalleApartados;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import puntodeventa.bd.ConexionBd;
import puntodeventa.bd.Ruta;

/**
 *
 * @author jafeth8
 */
public class ProductosParaAniadir extends javax.swing.JDialog {

    public static int idApartado=0;
    TableModel instanciaTableModel= new TableModel();
    TablaCompras instanciaTablaCompras=new TablaCompras();
    Buscadores instanciaBuscadores=new Buscadores();
    Carrito instanciaCarrito =new Carrito();
    TablaApartados instanciaTablaApartados=new TablaApartados();
    Productos instanciaTablaProductos=new Productos();
    TablaDetalleApartados instanciaTablaDetalleApartados=new TablaDetalleApartados();
    /**
     * Creates new form ProductosParaAniadir
     */
    public ProductosParaAniadir(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        instanciaTablaCompras.truncarTablaTcompras("TRUNCATE "+Ruta.nametablaTcomprasAdditions);
        instanciaTableModel.mostrarDatosProductos("", tablaProductos);
        instanciaTableModel.datosTablaTcompras("", tablaProductosAgregados,Ruta.nametablaTcomprasAdditions);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuTablaProductos = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenuTablaAgregados = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        panelFondo = new javax.swing.JPanel();
        panelEncabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldCantidad = new javax.swing.JTextField();
        comboBox = new javax.swing.JComboBox<>();
        textFieldBuscador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldDescuento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductosAgregados = new javax.swing.JTable();
        panelInferior = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();

        jMenuItem1.setText("Agregar producto a apartado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenuTablaProductos.add(jMenuItem1);

        jMenuItem2.setText("Quitar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenuTablaAgregados.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("CANTIDAD:");

        textFieldCantidad.setForeground(new java.awt.Color(255, 51, 51));
        textFieldCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldCantidad.setText("1");

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DESCRIPCION", "CATEGORIA" }));

        textFieldBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuscadorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("DESCUENTO:");

        textFieldDescuento.setText("0.0");

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textFieldBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductos.setComponentPopupMenu(jPopupMenuTablaProductos);
        jScrollPane1.setViewportView(tablaProductos);

        tablaProductosAgregados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductosAgregados.setComponentPopupMenu(jPopupMenuTablaAgregados);
        jScrollPane2.setViewportView(tablaProductosAgregados);

        btnAgregar.setText("LISTO!!");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("TOTAL:");

        labelTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTotal.setText("0.0");

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(jLabel3)
                    .addComponent(labelTotal))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2)
            .addComponent(panelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscadorActionPerformed
        
        instanciaBuscadores.searchByBarCode(tablaProductos, tablaProductosAgregados, textFieldDescuento, textFieldBuscador, comboBox, textFieldCantidad, labelTotal,Ruta.nametablaTcomprasAdditions);
    }//GEN-LAST:event_textFieldBuscadorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        int fila = tablaProductos.getSelectedRow();
        if (fila >= 0) {  
            instanciaCarrito.addCarrito(tablaProductos, tablaProductosAgregados, textFieldDescuento, textFieldBuscador, labelTotal,Ruta.nametablaTcomprasAdditions);
        }else {
            JOptionPane.showMessageDialog(null,"no selecciono producto");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        int fila=tablaProductosAgregados.getSelectedRow();
        float total;
        if(fila>=0) {
            total = instanciaTablaCompras.obtenerSumatoriaSubtotalTablaTcompras(Ruta.nametablaTcomprasAdditions);
            String descripcionProducto=tablaProductosAgregados.getValueAt(fila, 2).toString();
            String subtotaltabla=tablaProductosAgregados.getValueAt(fila, 4).toString();
            float calcula2 = (Float.parseFloat(subtotaltabla));
            total=(total-calcula2);
            labelTotal.setText(""+total);
            instanciaTablaCompras.eliminarRegistroTablaTcompras(descripcionProducto,Ruta.nametablaTcomprasAdditions);
            //mostrarProductosTcompras("");
            instanciaTableModel.datosTablaTcompras("", tablaProductosAgregados,Ruta.nametablaTcomprasAdditions);
        }else {
            JOptionPane.showMessageDialog(null,"no selecciono un producto");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Float totalAgregado;
        int filas=tablaProductosAgregados.getRowCount();
        
        ConexionBd cc = ConexionBd.obtenerInstancia();
        Connection cn = cc.conexion();
        PreparedStatement psAumentarDeudaAndTotal=null,psInsertDetalleApartados=null,psActualizaCantidadProductos=null;
        if(filas>0) {

            if(idApartado==0) {
                JOptionPane.showMessageDialog(null,"Los productos a agregar no estan vinculados con ningun apartado");
                return;
            }
    
            try {
                cn.setAutoCommit(false);
                
                //idApartado se inicializa desde la clase 'DetalleApartados'
                float totalOriginal =instanciaTablaApartados.obtenerTotalTablaApartados(idApartado);
                float deudaOriginal=instanciaTablaApartados.obtenerDeudaTablaApartados(idApartado);
                //el metotodo obtenerSumatoriaSubtotalTablaTcompras() devolvera null haciendo que lanze la excepcion NullPointerException deteniendo asi
                //la ejecucion del programa y evitando que se complete la transaccion, un hechizo simple pero efectivo XD (dependiendo de la ubicacion o del flujo del mismo puede que funcione o no)
                //en este caso funciona porque es el primer metodo que se ejecuta y por lo tanto bota el programa ignorando asi las demas instrucciones
                //TODO: lanzar aviso de "volver a intentarlo" 
                totalAgregado=instanciaTablaCompras.obtenerSumatoriaSubtotalTablaTcompras(Ruta.nametablaTcomprasAdditions);
                
                //aumentarTotal_y_DeudaTablaApartados
                float resultadoTotal=totalOriginal+totalAgregado;
                float resultadoDeuda=deudaOriginal+totalAgregado;
                psAumentarDeudaAndTotal = cn.prepareStatement("UPDATE apartados SET total='"+resultadoTotal+"',deuda='"+resultadoDeuda+"' WHERE id_apartado='"+idApartado+"'");
                psAumentarDeudaAndTotal.executeUpdate();

                String fechaRegistroDetalleApartado=LocalDate.now().toString();

                for (int i = 0; i <filas; i++) {
                    int idProducto=Integer.parseInt(tablaProductosAgregados.getValueAt(i,0).toString());
                    float cantidadDeApartados=Float.parseFloat(tablaProductosAgregados.getValueAt(i,1).toString());
                    String descripcion=tablaProductosAgregados.getValueAt(i,2).toString();
                    float precioUnitario=Float.parseFloat(tablaProductosAgregados.getValueAt(i, 3).toString());
                    float costoUnitario=instanciaTablaProductos.obtenerCostoProductoTablaProducto(idProducto);
                    float descuento=Float.parseFloat(tablaProductosAgregados.getValueAt(i,5).toString());
                    //instanciaTablaDetalleApartados.insertDetalleApartados(idApartado,idProducto, costoUnitario, precioUnitario, cantidadDeApartados,fechaRegistroDetalleApartado,descuento);
                    psInsertDetalleApartados= cn.prepareStatement("INSERT INTO detalle_apartados"
                    + "(fk_id_apartado,fk_id_producto,costo_unitario,precio_unitario,cantidad,fecha_registro,descuento) VALUES (?,?,?,?,?,?,?)");
                    psInsertDetalleApartados.setInt(1, idApartado);
                    psInsertDetalleApartados.setInt(2, idProducto);
                    psInsertDetalleApartados.setFloat(3, costoUnitario);
                    psInsertDetalleApartados.setFloat(4, precioUnitario);
                    psInsertDetalleApartados.setFloat(5, cantidadDeApartados);
                    psInsertDetalleApartados.setString(6, fechaRegistroDetalleApartado);
                    psInsertDetalleApartados.setFloat(7, descuento);
                    psInsertDetalleApartados.executeUpdate();
                    float cantidadTablaProducto=instanciaTablaProductos.obtenerCantidadTablaProducto(idProducto);
                    
                    //actualizarCantidadProductos
                    float cantidadRestante=cantidadTablaProducto-cantidadDeApartados;
                    psActualizaCantidadProductos = cn.prepareStatement("UPDATE productos SET cantidad='"+cantidadRestante+"' WHERE ID='"+idProducto+"'");
                    psActualizaCantidadProductos.executeUpdate();
                }
                
                cn.commit();
                JOptionPane.showMessageDialog(null,"Nuevos productos fueron agregados a este apartado");
                instanciaTableModel.mostrarDatosProductos("",VentanaPrincipal.jTablaProductos);
                idApartado=0;
                instanciaTablaCompras.truncarTablaTcompras("TRUNCATE "+Ruta.nametablaTcomprasAdditions);
                dispose();
            }catch (Exception e) {
                System.out.println("puntodeventa.ProductosParaAniadir.jButton1ActionPerformed() rollback()");
                JOptionPane.showMessageDialog(null,"por favor intentelo nuevamente o intentelo mas tarde",e.getMessage(),JOptionPane.WARNING_MESSAGE);
                try {
                    cn.rollback();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showInternalMessageDialog(null,"error rollback en el evento para agregar productos al apartado "+ex.getMessage(),"no se pudo hacer rollback puntodeventa.ProductosParaAniadir", JOptionPane.WARNING_MESSAGE);
                }
                dispose();
            }finally{
                System.out.println("finally puntodeventa.ProductosParaAniadir.jButton1ActionPerformed()");
                try {
                    cn.setAutoCommit(true);
                    //PreparedStatement psAumentarDeudaAndTotal=null,psInsertDetalleApartados,psActualizaCantidadProductos;
                    if(psAumentarDeudaAndTotal!=null)psAumentarDeudaAndTotal.close();
                    if(psInsertDetalleApartados!=null)psInsertDetalleApartados.close();
                    if(psActualizaCantidadProductos!=null)psActualizaCantidadProductos.close();
                    if(cn!=null)cn.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showInternalMessageDialog(null,"fallo al establecer autocommit en true en el evento para agregar productos al apartado "+ex.getMessage(),"autocommit en true fallo  puntodeventa.ProductosParaAniadir", JOptionPane.WARNING_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"La tabla esta vacia");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosParaAniadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosParaAniadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosParaAniadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosParaAniadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProductosParaAniadir dialog = new ProductosParaAniadir(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenuTablaAgregados;
    private javax.swing.JPopupMenu jPopupMenuTablaProductos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTable tablaProductosAgregados;
    private javax.swing.JTextField textFieldBuscador;
    private javax.swing.JTextField textFieldCantidad;
    private javax.swing.JTextField textFieldDescuento;
    // End of variables declaration//GEN-END:variables
}
