/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa;

import helpers.Buscadores;
import helpers.MetodosImprimir;
import helpers.TableModel;
import helpers.backup.RespaldoAutomatico;
import helpers.backup.RespaldoBd;
import helpers.compras.Carrito;
import helpers.compras.ComprasPorApartado;
import helpers.sql.Productos;
import helpers.sql.TablaCompras;
import java.awt.Graphics;
import java.io.IOException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import puntodeventa.bd.Ruta;

/**
 *
 * @author jafeth888
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private static AgregarDatos instanciaAgregarDatos;
    private static ActualizarProducto instanciaActualizarProducto;
    private static RegistrarClientes instanciaRegistrarClientes;
    private static VerApartados instanciaVerApartados;
    private static Inventario instanciaInventario;
    public static Insumos instanciaInsumos;
    public static ProductosAgotados instanciaProductosAgotados;
    public static VerVentas instanciaVerVentas;
    public static VerUtilidades instanciaVerUtilidades;
    public static VerProductosEliminados instanciaProductosEliminados;
    public static RegistrarDatosTicket instanciaRegistrarDatosTicket;
    private RespaldoBd instanciaRespaldoBd=new RespaldoBd();
    TableModel tableModel=new TableModel();
    TablaCompras tablaCompras=new TablaCompras();
    ComprasPorApartado instanciaComprasPorApartado = new ComprasPorApartado();
    MetodosImprimir instanciaMetodosImprimir=new MetodosImprimir();
    public static int setClienteId=0;
    public static String NombreClienteApartados="";
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        //this.setContentPane(new ImagenFondo());
        initComponents();
        tableModel.mostrarDatosProductos("", jTablaProductos);
        tableModel.datosTablaTcompras("", jtablaCompras,"tcompras");
        jLabelTotal.setText(""+tablaCompras.obtenerSumatoriaSubtotalTablaTcompras("tcompras"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioLabel = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnCredito = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblCantidad = new javax.swing.JLabel();
        textFieldcantidadProductos = new javax.swing.JTextField();
        comboBoxBusqueda = new javax.swing.JComboBox<>();
        codigoBarra = new javax.swing.JTextField();
        labelDescuento = new javax.swing.JLabel();
        textFieldDescuento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaProductos = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtablaCompras = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        botonPagar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabelCambio = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        itemAgregarClientes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuReportes = new javax.swing.JMenu();
        jMenuItemInventario = new javax.swing.JMenuItem();
        jMenuItemInsumos = new javax.swing.JMenuItem();
        jMenuItemProductosAgotados = new javax.swing.JMenuItem();
        jMenuItemHistorialVentas = new javax.swing.JMenuItem();
        jMenuItemVerUtilidades = new javax.swing.JMenuItem();
        jMenuItemVerProductosEliminados = new javax.swing.JMenuItem();
        jMenuItemcCrearRespaldo = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        usuarioLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usuarioLabel.setForeground(new java.awt.Color(255, 51, 51));
        usuarioLabel.setText("User");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        btnAgregar.setText("AGREGAR PRODUCTO");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/credito.png"))); // NOI18N
        btnCredito.setText("A CREDITO");
        btnCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditoActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        jButton3.setText("ELIMINAR PRODUCTO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        jButton4.setText("ACTUALIZAR PRODUCTO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCantidad.setText("CANTIDAD:");

        textFieldcantidadProductos.setText("1");

        comboBoxBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DESCRIPCION", "CATEGORIA" }));
        comboBoxBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxBusquedaActionPerformed(evt);
            }
        });

        codigoBarra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigoBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoBarraActionPerformed(evt);
            }
        });
        codigoBarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoBarraKeyReleased(evt);
            }
        });

        labelDescuento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDescuento.setText("DESCUENTO:");

        textFieldDescuento.setText("0.0");

        jTablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablaProductos);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        jButton5.setText("NUEVA VENTA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        jButton6.setText("AGREGAR A CARRITO");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cotizacion.png"))); // NOI18N
        jButton7.setText("COTIZAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jButton8.setText("CANCELAR PRODUCTO");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jtablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtablaCompras);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("TOTAL $ :");

        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTotal.setText("0.0");

        botonPagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dinero.png"))); // NOI18N
        botonPagar.setText("PAGAR");
        botonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setText("CAMBIO:");

        jLabelCambio.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelCambio.setText("0.0");

        jMenu2.setText("USUARIOS");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("CLIENTES");

        itemAgregarClientes.setText("Agregar clientes");
        itemAgregarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarClientesActionPerformed(evt);
            }
        });
        jMenu3.add(itemAgregarClientes);

        jMenuItem1.setText("Registrar abono de creditos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Ver clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Clientes eliminados");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenuReportes.setText("REPORTES");

        jMenuItemInventario.setText("INVENTARIO");
        jMenuItemInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInventarioActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItemInventario);

        jMenuItemInsumos.setText("REGISTRAR INSUMOS");
        jMenuItemInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInsumosActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItemInsumos);

        jMenuItemProductosAgotados.setText("PRODUCTOS AGOTADOS");
        jMenuItemProductosAgotados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductosAgotadosActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItemProductosAgotados);

        jMenuItemHistorialVentas.setText("HISTORIAL VENTAS");
        jMenuItemHistorialVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHistorialVentasActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItemHistorialVentas);

        jMenuItemVerUtilidades.setText("VER UTILIDADES");
        jMenuItemVerUtilidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerUtilidadesActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItemVerUtilidades);

        jMenuItemVerProductosEliminados.setText("VER PRODUCTOS ELIMINADOS");
        jMenuItemVerProductosEliminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerProductosEliminadosActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItemVerProductosEliminados);

        jMenuItemcCrearRespaldo.setText("CREAR RESPALDO");
        jMenuItemcCrearRespaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemcCrearRespaldoActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItemcCrearRespaldo);

        jMenuItem4.setText("REGISTRAR RUTA RESPALDO");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItem4);

        jMenuBar1.add(jMenuReportes);

        jMenu1.setText("IMPRESORA");

        jMenuItem5.setText("Datos de impresion");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("CERRAR SESION");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(botonPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldcantidadProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboBoxBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codigoBarra)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDescuento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldDescuento)))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(usuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldcantidadProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDescuento)
                    .addComponent(textFieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabelTotal)
                            .addComponent(botonPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabelCambio))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(instanciaAgregarDatos==null){
            instanciaAgregarDatos=new AgregarDatos();
        }
        instanciaAgregarDatos.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        int fila=jTablaProductos.getSelectedRow();
        Productos helperProducto = new Productos();
        String codigoBarra,cantidadProductos,descripcion,costoUnitario,precioUnitario;
        String categoria;
        if(fila>=0){
            int idProducto= Integer.parseInt(jTablaProductos.getValueAt(fila, 0).toString().toString());
            if(instanciaActualizarProducto==null){
                instanciaActualizarProducto=new ActualizarProducto(this, rootPaneCheckingEnabled);
            }
            
            codigoBarra = jTablaProductos.getValueAt(fila, 1).toString();
            //cantidad=jTablaProductos.getValueAt(fila, 2).toString();
            descripcion = jTablaProductos.getValueAt(fila, 3).toString();
            precioUnitario=jTablaProductos.getValueAt(fila, 4).toString();
            costoUnitario=jTablaProductos.getValueAt(fila, 5).toString();
            categoria=helperProducto.obtenerCategoriaProducto(idProducto);
            cantidadProductos=helperProducto.obtenerCantidadProductoDescripcion(descripcion);
            
            instanciaActualizarProducto.establecerTextoCodigoBarra(codigoBarra);
            instanciaActualizarProducto.establecerTextoDescripcion(descripcion);
            instanciaActualizarProducto.establecerTextoCantidadActual(cantidadProductos);
            instanciaActualizarProducto.establecerTextoCostoUnitario(costoUnitario);
            instanciaActualizarProducto.establecerTextoPrecioUnitario(precioUnitario);
            instanciaActualizarProducto.establecerTextoCategoria(categoria);
            instanciaActualizarProducto.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(rootPane,"Debe seleccionar un producto");
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        codigoBarra.requestFocus();
    }//GEN-LAST:event_formWindowGainedFocus

    private void codigoBarraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoBarraKeyReleased
        // TODO add your handling code here:
        //Buscadores buscador =new Buscadores();
        //buscador.searchByBarCode(jTablaProductos,jtablaCompras,textFieldDescuento, codigoBarra, comboBoxBusqueda, textFieldcantidadProductos, jLabelTotal,Ruta.nametablaTcompras);
    }//GEN-LAST:event_codigoBarraKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Productos schemaProducto=new Productos();
     
        int fila=jTablaProductos.getSelectedRow();
        int idProducto = Integer.parseInt(jTablaProductos.getValueAt(fila, 0).toString());
        if (fila == -1) {
                JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UN PRODUCTO", "Mensaje de Error",JOptionPane.ERROR_MESSAGE);
        } else {
            int opcion=JOptionPane.showConfirmDialog(null,"Esta seguro de eliminar este producto","Advertencia",JOptionPane.YES_NO_OPTION);
            System.out.println("opcion " +opcion);
            if(opcion==0) {
                schemaProducto.actualizarStateTablaProductos(idProducto, 3); // 3 es eliminado en la tabla sstate
                JOptionPane.showMessageDialog(null, "producto eliminado satisfactoriamente");
                tableModel.mostrarDatosProductos("", jTablaProductos);
                if(codigoBarra.getText().equals("")) {
                    tableModel.mostrarDatosProductos("",jTablaProductos);
                }else {
                    tableModel.mostrarDatosProductos(codigoBarra.getText(),jTablaProductos);
                }
            }	
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        tablaCompras.truncarTablaTcompras("TRUNCATE tcompras");		
        jLabelTotal.setText("0.0");
        jLabelCambio.setText("0.0");
        JOptionPane.showMessageDialog(null, "SE GENERO UNA NUEVA VENTA :D");
        tableModel.datosTablaTcompras("", jtablaCompras,"tcompras");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Carrito carrito = new Carrito(this);
        //carrito.addCarrito(jTablaProductos, jtablaCompras,textFieldDescuento);
        carrito.addCarrito(jTablaProductos, jtablaCompras, textFieldDescuento, codigoBarra, jLabelTotal,Ruta.nametablaTcompras);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void comboBoxBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxBusquedaActionPerformed
        // TODO add your handling code here:
        codigoBarra.requestFocus();
    }//GEN-LAST:event_comboBoxBusquedaActionPerformed

    private void botonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagarActionPerformed
        // TODO add your handling code here:
        Carrito carrito=new Carrito();
        carrito.pagar(jTablaProductos, jtablaCompras, jLabelTotal, jLabelCambio, usuarioLabel,true);
    }//GEN-LAST:event_botonPagarActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int fila=jtablaCompras.getSelectedRow();
        float total,subTotal;
        System.out.println("la fila es: "+fila);
        if(fila>=0){
            total=tablaCompras.obtenerSumatoriaSubtotalTablaTcompras(Ruta.nametablaTcompras);
            String descripcionProducto=jtablaCompras.getValueAt(fila, 2).toString();
            String subTotaltabla=jtablaCompras.getValueAt(fila, 4).toString();
            subTotal=Float.parseFloat(subTotaltabla);
            total=total-subTotal;
            jLabelTotal.setText(""+total);
            tablaCompras.eliminarRegistroTablaTcompras(descripcionProducto,Ruta.nametablaTcompras);
            tableModel.datosTablaTcompras("", jtablaCompras,Ruta.nametablaTcompras);
        }else{
            JOptionPane.showMessageDialog(null,"NO SELECCIONO PRODUCTO","Mensaje de Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        float total;
        total=(float) tablaCompras.obtenerSumatoriaSubtotalTablaTcompras(Ruta.nametablaTcompras);
        if(total==0){
            JOptionPane.showMessageDialog(null,"DEBES GENERAR UNA VENTA PARA COTIZAR","Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int pre=JOptionPane.showConfirmDialog(null, "DESEA IMPRIMIR LA COTIZACION ?","",JOptionPane.YES_NO_OPTION);
        if(pre==0){
            instanciaMetodosImprimir.imprimirCotizacion(jtablaCompras, jLabelTotal, usuarioLabel);
        }else{
            JOptionPane.showMessageDialog(null, "Cancelado","Mensaje de aviso",JOptionPane.CANCEL_OPTION);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditoActionPerformed

        MetodosImprimir instanciaImprimir=new MetodosImprimir();
        /*---VARIABLES: PARA INSERTAR EN TABLA APARTADOS*/
        int idCliente;
        int id_producto;// perfectamente se podria utilizar (setClienteId) la variable estatica de la clase, pero para no revolver variables la dejo XD
        int cantidadIngresada;
        /*---FIN DE VARIABLES:PARA INSERTAR EN TABLA APARTADOS */
        float total=0;
        total=tablaCompras.obtenerSumatoriaSubtotalTablaTcompras(Ruta.nametablaTcompras);
        int filas=jtablaCompras.getRowCount();
        
        if(filas==0){
            JOptionPane.showMessageDialog(null,"Primero debes agregar productos al carrito");
            return;
        }
        JOptionPane.showMessageDialog(null,"enseguida seleccione al cliente que hara el apartado");
        MostrarClientes cliente=new MostrarClientes(this, rootPaneCheckingEnabled);
        cliente.setVisible(rootPaneCheckingEnabled);
        
        idCliente=setClienteId;//setIdCliente es una variable estatica para recibir datos de la ventana MostrarClientes
        if(idCliente==0) {//si id cliente es igual a cero significa que no se establecio un idCliente, por lo tanto la ventana fue cerrada
            JOptionPane.showMessageDialog(null, "operacion cancelada" ,"NO SELECCIONO AL CLIENTE!!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String fechaApartado=LocalDate.now().toString();
        boolean exito=instanciaComprasPorApartado.apartarProductos(jtablaCompras, idCliente, total, fechaApartado, total, Ruta.ESTADO_DEUDA_TABLA_APARTADOS);
        
        int opcion=403;
        if(exito==true)opcion=JOptionPane.showConfirmDialog(null,"desea imprimir el apartado?","" ,JOptionPane.YES_NO_OPTION);
        if(opcion==0){
            for (int i = 0; i <2; i++) {
                instanciaMetodosImprimir.imprimirApartado(jtablaCompras, jLabelTotal, usuarioLabel, NombreClienteApartados);
            }
        }
        if(exito==true)JOptionPane.showMessageDialog(null,"Apartado realizado correctamente");
        tablaCompras.truncarTablaTcompras("TRUNCATE "+Ruta.nametablaTcompras+"");
        jLabelTotal.setText("0.0");
	jLabelCambio.setText("0.0");
        setClienteId=0;
	NombreClienteApartados="";
        tableModel.mostrarDatosProductos("",jTablaProductos);
        tableModel.datosTablaTcompras("", jtablaCompras, Ruta.nametablaTcompras);
    }//GEN-LAST:event_btnCreditoActionPerformed

    private void itemAgregarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarClientesActionPerformed
        if(instanciaRegistrarClientes==null){
            instanciaRegistrarClientes=new RegistrarClientes(this, rootPaneCheckingEnabled);
        }
        
        instanciaRegistrarClientes.setVisible(true);
    }//GEN-LAST:event_itemAgregarClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        instanciaVerApartados=new VerApartados(this, rootPaneCheckingEnabled);
        
        instanciaVerApartados.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        GestionarClientes instanciaGestionarClientes = new GestionarClientes(null,true);
        instanciaGestionarClientes.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        MostrarClientesEliminados instanciaClientesEliminados = new MostrarClientesEliminados(null,true);
        instanciaClientesEliminados.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItemInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInventarioActionPerformed
        
        if(instanciaInventario==null){
            instanciaInventario=new Inventario();
        }
        instanciaInventario.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItemInventarioActionPerformed

    private void jMenuItemInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInsumosActionPerformed
        
        if(instanciaInsumos==null){
            instanciaInsumos=new Insumos();
        }
        instanciaInsumos.setVisible(true);
    }//GEN-LAST:event_jMenuItemInsumosActionPerformed

    private void jMenuItemProductosAgotadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductosAgotadosActionPerformed

        //inicializacion de objeto de esta manera fue necesaria al ser de tipo JDialog: no pudo controlar la inicializacion del objeto al mostrar
        //los datos,(mirar la clase Insumos en el metodo mostrar datos para entender el contexto)
        instanciaProductosAgotados=new ProductosAgotados(this,true);
        
        instanciaProductosAgotados.setVisible(true);
    }//GEN-LAST:event_jMenuItemProductosAgotadosActionPerformed

    private void jMenuItemHistorialVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHistorialVentasActionPerformed
        
        if(instanciaVerVentas==null){
            instanciaVerVentas=new VerVentas();
        }
        instanciaVerVentas.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemHistorialVentasActionPerformed

    private void jMenuItemVerUtilidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerUtilidadesActionPerformed
        
        instanciaVerUtilidades= new VerUtilidades(this, rootPaneCheckingEnabled);
        instanciaVerUtilidades.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemVerUtilidadesActionPerformed

    private void jMenuItemVerProductosEliminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerProductosEliminadosActionPerformed
        // TODO add your handling code here:
        
        if(instanciaProductosEliminados==null){
            instanciaProductosEliminados=new VerProductosEliminados(this, rootPaneCheckingEnabled);
        }
        
        instanciaProductosEliminados.setVisible(rootPaneCheckingEnabled);
        
    }//GEN-LAST:event_jMenuItemVerProductosEliminadosActionPerformed

    private void jMenuItemcCrearRespaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemcCrearRespaldoActionPerformed
        try {
            // TODO add your handling code here:
            instanciaRespaldoBd.crearRespaldoBd();
        } catch (IOException ex) {
           ex.printStackTrace();
           JOptionPane.showMessageDialog(rootPane,"Error intentelo mas tarde: "+ex.getMessage(),"Error al respaldar datos",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemcCrearRespaldoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.out.println("Ventana cerrada!!!");
        if (instanciaRespaldoBd.registro_ruta_respaldo()) {
            RespaldoAutomatico instancia = new RespaldoAutomatico(this, rootPaneCheckingEnabled);
            instancia.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        System.out.println("Ventana abierta");
        if (instanciaRespaldoBd.registro_ruta_respaldo() != true) {
            JOptionPane.showMessageDialog(this, "No hay ninguna ruta registrada para el respaldo automatico", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        RutaRespaldoAutomatico instancia=new RutaRespaldoAutomatico(this, rootPaneCheckingEnabled);
        instancia.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void codigoBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoBarraActionPerformed
        // TODO add your handling code here:
        Buscadores buscador =new Buscadores();
        buscador.searchByBarCode(jTablaProductos,jtablaCompras,textFieldDescuento, codigoBarra, comboBoxBusqueda, textFieldcantidadProductos, jLabelTotal,Ruta.nametablaTcompras);
    }//GEN-LAST:event_codigoBarraActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if(instanciaRegistrarDatosTicket==null){
            instanciaRegistrarDatosTicket= new RegistrarDatosTicket(this, rootPaneCheckingEnabled);
        }
        
        instanciaRegistrarDatosTicket.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPagar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCredito;
    public static javax.swing.JTextField codigoBarra;
    private javax.swing.JComboBox<String> comboBoxBusqueda;
    private javax.swing.JMenuItem itemAgregarClientes;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCambio;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemHistorialVentas;
    private javax.swing.JMenuItem jMenuItemInsumos;
    private javax.swing.JMenuItem jMenuItemInventario;
    private javax.swing.JMenuItem jMenuItemProductosAgotados;
    private javax.swing.JMenuItem jMenuItemVerProductosEliminados;
    private javax.swing.JMenuItem jMenuItemVerUtilidades;
    private javax.swing.JMenuItem jMenuItemcCrearRespaldo;
    private javax.swing.JMenu jMenuReportes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTablaProductos;
    private javax.swing.JTable jtablaCompras;
    private javax.swing.JLabel labelDescuento;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JTextField textFieldDescuento;
    private javax.swing.JTextField textFieldcantidadProductos;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables

    public class ImagenFondo extends JPanel{

        @Override
        public void paint(Graphics g) {
            ImageIcon imagen = new ImageIcon(getClass().getResource("../img/fondoImagen.jpg"));
            g.drawImage(imagen.getImage(),0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g); 
        }
    }
}
